#!/usr/bin/env python3
"""Builds the country-flag sprite sheet from Tossface's SVG release.

    python3 tool/build_flag_sprite.py --svg-dir <TossFace-Svg-v1-6>

The sheet is a 26x26 grid of 26pt cells covering every ISO alpha-2 code from
AA to ZZ, so a flag's cell is `(first letter, second letter)` and there is no
ordering to keep in step — nothing is maintained on either side. Codes Tossface
has no artwork for stay transparent, which is also the right fallback for a
code that is not a country at all.

Writes the 1x sheet plus 2x and 3x variants for Flutter's asset resolution.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "assets" / "flags"

CELL = 26
# One column and one row per letter: cell = (iso[0], iso[1]).
LETTERS = 26
SCALES = (1, 2, 3)

REGIONAL_INDICATOR_BASE = 0x1F1E6


def all_codes() -> list[str]:
    return [
        chr(ord("A") + first) + chr(ord("A") + second)
        for first in range(LETTERS)
        for second in range(LETTERS)
    ]


def svg_name(iso: str) -> str:
    """Tossface names a flag by its two regional-indicator code points."""
    points = [REGIONAL_INDICATOR_BASE + (ord(c) - ord("A")) for c in iso]
    return "_".join(f"u{point:X}" for point in points) + ".svg"


def render(svg: Path, size: int, into: Path) -> Image.Image:
    subprocess.run(
        [
            "rsvg-convert",
            "--width", str(size),
            "--height", str(size),
            "--keep-aspect-ratio",
            "-o", str(into),
            str(svg),
        ],
        check=True,
        capture_output=True,
    )
    return Image.open(into).convert("RGBA")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--svg-dir",
        type=Path,
        required=True,
        help="unpacked TossFace-Svg release directory",
    )
    args = parser.parse_args()

    drawn = [iso for iso in all_codes() if (args.svg_dir / svg_name(iso)).exists()]
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="flag-sprite-") as scratch:
        for scale in SCALES:
            cell = CELL * scale
            sheet = Image.new(
                "RGBA", (LETTERS * cell, LETTERS * cell), (0, 0, 0, 0)
            )
            for iso in drawn:
                flag = render(
                    args.svg_dir / svg_name(iso),
                    cell,
                    Path(scratch) / f"{iso}-{scale}.png",
                )
                column = ord(iso[0]) - ord("A")
                row = ord(iso[1]) - ord("A")
                # Tossface flags are square; centre in case one is not.
                x = column * cell + (cell - flag.width) // 2
                y = row * cell + (cell - flag.height) // 2
                sheet.alpha_composite(flag, (x, y))

            target = (
                OUTPUT_DIR / "flags.png"
                if scale == 1
                else OUTPUT_DIR / f"{scale}.0x" / "flags.png"
            )
            target.parent.mkdir(parents=True, exist_ok=True)
            sheet.save(target, optimize=True)
            print(f"{target.relative_to(ROOT)}  {sheet.width}x{sheet.height}")

    (OUTPUT_DIR / "README.md").write_text(
        "# Country flags\n\n"
        "Generated by `tool/build_flag_sprite.py` from "
        "[Tossface](https://github.com/toss/tossface).\n\n"
        f"A {LETTERS}x{LETTERS} grid of {CELL}pt cells covering every ISO\n"
        "alpha-2 code. A flag's cell is its two letters — column from the\n"
        "first, row from the second — so nothing here needs an index and\n"
        "adding a country is a regenerate, not a table edit.\n\n"
        f"{len(drawn)} of {LETTERS * LETTERS} cells carry artwork; the rest\n"
        "are transparent, which is the right fallback for a code that is not\n"
        "a country.\n",
        encoding="utf-8",
    )
    print(f"{len(drawn)} flags in a {LETTERS}x{LETTERS} grid")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
