#!/bin/sh
#
# ci_post_clone.sh — Xcode Cloud post-clone setup for this Flutter + native-TDLib app.
#
# Xcode Cloud checks out the repo clean and runs `xcodebuild` directly, but several
# build inputs are NOT in git (they're generated by Flutter or by a native build):
#   - ios/Flutter/ephemeral/...           (incl. FlutterGeneratedPluginSwiftPackage)
#   - ios/Flutter/Generated.xcconfig
#   - lib/config/secrets.dart             (Telegram api id / hash)
#   - ios/tdjson/tdjson.xcframework       (native TDLib — git-ignored build artifact)
#   - ios/Pods/
# This script recreates all of them so the Xcode Cloud archive can build.
#
# REQUIRED Xcode Cloud environment variables (Workflow → Environment → Environment
# Variables):
#   TELEGRAM_API_ID     integer
#   TELEGRAM_API_HASH   string   (mark as Secret)
#   FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64
#                      base64 of ios/Runner/GoogleService-Info.plist
# Optional:
#   TGVOIP_WEBRTC_XCFRAMEWORK_URL
#                      override the pinned official Telegram iOS group-call XCFramework
#   TGVOIP_WEBRTC_XCFRAMEWORK_SHA256
#                      SHA-256 for the TgVoip override
#   SENTRY_AUTH_TOKEN        upload iOS dSYMs to Sentry when set
#   SENTRY_ORG               Sentry org slug for dSYM upload; defaults to nekoko
#   SENTRY_PROJECT           Sentry project slug for dSYM upload; defaults to mithka
#                            (the legacy numeric project ID 10 is normalized)
#   SENTRY_URL               Sentry base URL; defaults to https://sentry.nekoko.it
#
# The prebuilt tdjson.xcframework is hosted in the sibling mithka-tdjson repo
# rather than rebuilt here, because building TDLib + OpenSSL for iOS takes
# ~40 min. scripts/build-tdjson-ios.sh resolves the repository-pinned manifest,
# verifies the archive and installed framework, and never follows "latest".

set -e

FLUTTER_VERSION="3.44.2"
COCOAPODS_VERSION="1.17.0"
TGVOIP_RELEASE_TAG="tgvoip-telegram-ios-6e370e06d147"
TGVOIP_URL="${TGVOIP_WEBRTC_XCFRAMEWORK_URL:-https://github.com/iebb/mithka-tdjson/releases/download/${TGVOIP_RELEASE_TAG}/tgvoip-ios.xcframework.zip}"
TGVOIP_SHA256="${TGVOIP_WEBRTC_XCFRAMEWORK_SHA256:-a1da44189af3802fcc0900696c5cdc549ffc2e53c5a2a0bab713a208aefe2737}"
SQLITE3_VERSION="3.5.2"
SQLITE3_IOS_ARM64_ASSET="libsqlite3.arm64.ios.dylib"
SQLITE3_IOS_ARM64_SHA256="f1bc69a4304a21e472c15f849c34ae46539483cfa7ce901f54175c6d6cc17991"
SQLITE3_IOS_ARM64_URL="https://github.com/simolus3/sqlite3.dart/releases/download/sqlite3-${SQLITE3_VERSION}/${SQLITE3_IOS_ARM64_ASSET}"
CURL_RETRY_FLAGS="-fL --retry 5 --retry-delay 2 --connect-timeout 20"
if curl --help all 2>/dev/null | grep -q -- '--retry-all-errors'; then
  CURL_RETRY_FLAGS="$CURL_RETRY_FLAGS --retry-all-errors"
fi

retry() {
  attempts="$1"
  delay="$2"
  shift 2
  n=1
  while :; do
    "$@" && return 0
    status=$?
    if [ "$n" -ge "$attempts" ]; then
      echo "error: command failed after $attempts attempts: $*" >&2
      return "$status"
    fi
    echo "warning: command failed with exit $status; retry $((n + 1))/$attempts in ${delay}s: $*" >&2
    sleep "$delay"
    n=$((n + 1))
    delay=$((delay * 2))
  done
}

ensure_cocoapods() {
  installed_version="$(pod --version 2>/dev/null || true)"
  if [ "$installed_version" != "$COCOAPODS_VERSION" ]; then
    echo "▸ installing CocoaPods $COCOAPODS_VERSION"
    retry 3 10 sudo gem install cocoapods -v "$COCOAPODS_VERSION" --no-document
    hash -r
    installed_version="$(pod --version 2>/dev/null || true)"
  fi
  if [ "$installed_version" != "$COCOAPODS_VERSION" ]; then
    echo "error: expected CocoaPods $COCOAPODS_VERSION, found ${installed_version:-missing}" >&2
    exit 1
  fi
  echo "▸ using CocoaPods $installed_version"
}

pod_install_with_retry() {
  attempts=4
  delay=8
  n=1
  while :; do
    rm -rf Pods
    pod_install_args="--deployment"
    if [ -d LocalPods/tgvoip/TgVoipWebrtc.xcframework ]; then
      # The optional local binary pod is added after checkout, so it cannot be
      # represented in the lockfile used by source-only contributor builds.
      pod_install_args=""
    fi
    # shellcheck disable=SC2086 # optional CocoaPods argument is intentionally split.
    if pod install $pod_install_args; then
      return 0
    fi
    status=$?
    if [ "$n" -ge "$attempts" ]; then
      echo "error: pod install failed after $attempts attempts" >&2
      return "$status"
    fi
    echo "warning: pod install failed with exit $status; clearing transient CocoaPods state and retrying $((n + 1))/$attempts in ${delay}s" >&2
    cleanup_cocoapods_transients
    sleep "$delay"
    n=$((n + 1))
    delay=$((delay * 2))
  done
}

cleanup_cocoapods_transients() {
  find "${TMPDIR:-/tmp}" -maxdepth 1 \( -name 'CocoaPods-*' -o -name 'd20*' \) -exec rm -rf {} + 2>/dev/null || true
  pod cache clean --all >/dev/null 2>&1 || true
}

flutter_build_ios_config_with_retry() {
  attempts=4
  delay=8
  n=1
  while :; do
    if flutter build ios --config-only --release \
      --build-name="$XCODE_BUILD_NAME" \
      --build-number="$APP_BUILD_NUMBER" \
      --dart-define="GIT_COMMIT=$GIT_COMMIT" \
      --dart-define="SENTRY_DSN=${SENTRY_DSN:-}" \
      --dart-define="SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-production}"; then
      return 0
    fi
    status=$?
    if [ "$n" -ge "$attempts" ]; then
      echo "error: flutter build ios --config-only failed after $attempts attempts" >&2
      return "$status"
    fi
    echo "warning: flutter build ios --config-only failed with exit $status; clearing transient CocoaPods state and retrying $((n + 1))/$attempts in ${delay}s" >&2
    cleanup_cocoapods_transients
    sleep "$delay"
    n=$((n + 1))
    delay=$((delay * 2))
  done
}

prefetch_sqlite3_ios_arm64() {
  locked_version="$(
    awk '
      $0 == "  sqlite3:" { in_sqlite3 = 1; next }
      in_sqlite3 && $1 == "version:" {
        gsub(/"/, "", $2)
        print $2
        exit
      }
      in_sqlite3 && /^  [[:alnum:]_]/ { exit }
    ' pubspec.lock
  )"
  if [ "$locked_version" != "$SQLITE3_VERSION" ]; then
    echo "error: sqlite3 lock version $locked_version does not match pinned iOS binary $SQLITE3_VERSION" >&2
    return 1
  fi

  cache_key="$(printf '%s' "$SQLITE3_IOS_ARM64_SHA256" | cut -c 1-8)"
  cache_dir="$REPO/.dart_tool/hooks_runner/shared/sqlite3/build/download-${cache_key}"
  output="$cache_dir/libsqlite3.dylib"
  tmp="${output}.tmp.$$"
  mkdir -p "$cache_dir"

  if [ -f "$output" ] &&
    printf '%s  %s\n' "$SQLITE3_IOS_ARM64_SHA256" "$output" |
      shasum -a 256 -c - >/dev/null 2>&1; then
    echo "▸ using cached sqlite3 $SQLITE3_VERSION iOS arm64 binary"
    return 0
  fi

  echo "▸ downloading sqlite3 $SQLITE3_VERSION iOS arm64 binary"
  rm -f "$tmp"
  # shellcheck disable=SC2086 # CURL_RETRY_FLAGS is intentionally split.
  if ! retry 3 5 curl $CURL_RETRY_FLAGS --max-time 120 "$SQLITE3_IOS_ARM64_URL" -o "$tmp"; then
    rm -f "$tmp"
    return 1
  fi
  if ! printf '%s  %s\n' "$SQLITE3_IOS_ARM64_SHA256" "$tmp" |
    shasum -a 256 -c -; then
    rm -f "$tmp"
    return 1
  fi
  if ! mv "$tmp" "$output"; then
    rm -f "$tmp"
    return 1
  fi
  if ! printf '%s  %s\n' "$SQLITE3_IOS_ARM64_SHA256" "$output" |
    shasum -a 256 -c -; then
    rm -f "$output"
    return 1
  fi
}

decode_base64_to_file() {
  data="$1"
  output="$2"
  tmp="${output}.tmp"
  if printf '%s' "$data" | base64 --decode > "$tmp" 2>/dev/null ||
    printf '%s' "$data" | base64 -D > "$tmp" 2>/dev/null ||
    printf '%s' "$data" | base64 -d > "$tmp"; then
    mv "$tmp" "$output"
    return 0
  fi
  rm -f "$tmp"
  return 1
}

# Xcode Cloud checks the repo out here; fall back to walking up from this script.
REPO="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/../.." && pwd)}"
cd "$REPO"
echo "▸ repo root: $REPO"
GIT_COMMIT="$(git rev-parse --short HEAD)"
echo "▸ git commit: $GIT_COMMIT"

# Xcode Cloud runs xcodebuild after this script and can otherwise keep using
# stale Flutter values from the checked-in project, so pin both the version and
# the build number from pubspec.yaml.
RAW_VERSION="$(awk '/^version:/ { print $2; exit }' pubspec.yaml)"
test -n "$RAW_VERSION"
APP_BUILD_NAME="${RAW_VERSION%%+*}"
SOURCE_BUILD_NUMBER="${RAW_VERSION#*+}"
if [ "$SOURCE_BUILD_NUMBER" = "$RAW_VERSION" ] || [ -z "$SOURCE_BUILD_NUMBER" ]; then
  SOURCE_BUILD_NUMBER=1
fi
APP_BUILD_NUMBER="${CI_BUILD_NUMBER:-$SOURCE_BUILD_NUMBER}"
case "$APP_BUILD_NUMBER" in
  ''|*[!0-9]*)
    echo "error: expected a numeric iOS build number, got $APP_BUILD_NUMBER" >&2
    exit 1
    ;;
esac
# The same marketing train macOS uploads on: a nightly collapses onto X.Y.0 so
# App Store Connect sees one train whose builds differ by build number, rather
# than a version per night it would have to review from scratch. A release
# keeps the exact patch it is named for.
XCODE_BUILD_NAME="$(sh "$REPO/scripts/apple_marketing_version.sh" \
  "$APP_BUILD_NAME" "${CI_BRANCH:-${GITHUB_REF_NAME:-}}")"
echo "▸ iOS app version: $XCODE_BUILD_NAME+$APP_BUILD_NUMBER (source: $APP_BUILD_NAME)"
python3 - <<PY
from pathlib import Path
path = Path("ios/Runner.xcodeproj/project.pbxproj")
text = path.read_text()
text = __import__("re").sub(r"FLUTTER_BUILD_NAME = [^;]+;", "FLUTTER_BUILD_NAME = ${XCODE_BUILD_NAME};", text)
text = __import__("re").sub(r"MARKETING_VERSION = [^;]+;", "MARKETING_VERSION = ${XCODE_BUILD_NAME};", text)
text = __import__("re").sub(r"CURRENT_PROJECT_VERSION = (?!\"\\$\\(FLUTTER_BUILD_NUMBER\\)\")[^;]+;", "CURRENT_PROJECT_VERSION = ${APP_BUILD_NUMBER};", text)
path.write_text(text)
PY

# --- Flutter SDK (pinned) ---------------------------------------------------
if ! command -v flutter >/dev/null 2>&1; then
  echo "▸ installing Flutter $FLUTTER_VERSION"
  retry 3 10 git clone --depth 1 -b "$FLUTTER_VERSION" https://github.com/flutter/flutter.git "$HOME/flutter"
  export PATH="$HOME/flutter/bin:$PATH"
fi
flutter --version
ensure_cocoapods

# --- Telegram credentials → lib/config/secrets.dart ------------------------
: "${TELEGRAM_API_ID:?set TELEGRAM_API_ID in the Xcode Cloud workflow environment}"
: "${TELEGRAM_API_HASH:?set TELEGRAM_API_HASH in the Xcode Cloud workflow environment}"
echo "▸ writing lib/config/secrets.dart"
mkdir -p lib/config
cat > lib/config/secrets.dart <<EOF
class Secrets {
  static const int apiId = ${TELEGRAM_API_ID};
  static const String apiHash = '${TELEGRAM_API_HASH}';
  static bool get isConfigured => apiId != 0 && apiHash.isNotEmpty;
}
EOF

# --- Firebase config → ios/Runner/GoogleService-Info.plist ------------------
mkdir -p ios/Runner
if [ -n "${FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64:-}" ]; then
  echo "▸ writing ios/Runner/GoogleService-Info.plist"
  decode_base64_to_file "$FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64" ios/Runner/GoogleService-Info.plist
elif [ -f ios/Runner/GoogleService-Info.plist ]; then
  echo "▸ using existing ios/Runner/GoogleService-Info.plist"
else
  echo "error: set FIREBASE_IOS_GOOGLESERVICE_INFO_PLIST_B64 in the Xcode Cloud workflow environment" >&2
  exit 1
fi

# --- Native TDLib framework (git-ignored; manifest-pinned release artifact) --
echo "▸ preparing pinned tdjson.xcframework"
"$REPO/scripts/build-tdjson-ios.sh"

echo "▸ downloading TgVoipWebrtc.xcframework"
rm -rf ios/LocalPods/tgvoip/TgVoipWebrtc.xcframework /tmp/tgvoip.zip
# shellcheck disable=SC2086 # CURL_RETRY_FLAGS is intentionally split.
retry 4 5 curl $CURL_RETRY_FLAGS "$TGVOIP_URL" -o /tmp/tgvoip.zip
printf '%s  %s\n' "$TGVOIP_SHA256" /tmp/tgvoip.zip | shasum -a 256 -c -
unzip -q -o /tmp/tgvoip.zip -d ios/LocalPods/tgvoip
ls -d ios/LocalPods/tgvoip/TgVoipWebrtc.xcframework

# --- Flutter iOS build inputs (Generated.xcconfig, SPM plugins, plugin pods) --
# Flutter's generated Swift package owns plugins that publish SPM manifests.
# CocoaPods remains alongside it for the small set of plugins without SPM
# support and the local TgVoipWebrtc pod. The exported IPA is still responsible
# for carrying SwiftSupport; scripts/build-ios-appstore.sh validates that
# distribution artifact explicitly to prevent a recurrence of ITMS-90426.
echo "▸ generating Flutter iOS build inputs"
flutter config --enable-swift-package-manager
flutter precache --ios
flutter pub get
prefetch_sqlite3_ios_arm64
flutter_build_ios_config_with_retry
python3 - <<PY >> ios/Flutter/Generated.xcconfig
import os
import urllib.parse

dsn = os.environ.get("SENTRY_DSN", "")
environment = os.environ.get("SENTRY_ENVIRONMENT", "production")
print("SENTRY_DSN_ENCODED=" + urllib.parse.quote(dsn, safe=""))
print("SENTRY_ENVIRONMENT=" + environment.replace("\\n", "").replace("\\r", ""))
PY

# --- CocoaPods --------------------------------------------------------------
echo "▸ pod install"
cd ios
# Xcode Cloud can restore or leave behind a stale Pods sandbox. The archive
# phase compares Podfile.lock with Pods/Manifest.lock, so rebuild the sandbox
# from the checked-in lockfile before xcodebuild runs.
pod_install_with_retry
cp Podfile.lock Pods/Manifest.lock
diff -q Podfile.lock Pods/Manifest.lock
ls -l Podfile.lock Pods/Manifest.lock

echo "✓ ci_post_clone complete"
